"""
app/schemas/ai/brand_voice.py

Structured output schema for the Brand Voice Agent.
"""
from enum import Enum
from typing import List
from pydantic import BaseModel, Field


class IssueSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class BrandVoiceIssue(BaseModel):
    """
    A specific brand voice violation identified by the AI.
    """
    category: str = Field(..., description="The category of the issue (e.g., Tone, Terminology).")
    description: str = Field(..., description="A description of the issue.")
    severity: IssueSeverity = Field(..., description="The severity of the issue.")


class BrandVoiceOutput(BaseModel):
    """
    Structured output generated by the AI Brand Voice Agent.
    """
    compliant: bool = Field(..., description="Whether the original draft is fully compliant without needing changes.")
    brand_score: float = Field(..., description="Score representing alignment with the brand kit (0.0 to 1.0).")
    revised_content: str = Field(..., description="The revised content, or the original content if no changes were needed.")
    issues: List[BrandVoiceIssue] = Field(default_factory=list, description="List of identified issues.")
    changes: List[str] = Field(default_factory=list, description="Summary of changes made.")
