"""
app/schemas/ai/content_plan.py

Structured output schema for the Content Planner Agent.
"""
from typing import List, Optional
from pydantic import BaseModel, Field


class ContentSection(BaseModel):
    """
    A single section or part of the planned content.
    """
    heading: str = Field(..., min_length=1, description="The heading or main idea of the section.")
    objective: str = Field(..., min_length=1, description="What this section aims to achieve.")
    key_points: List[str] = Field(..., max_length=10, description="List of specific points to cover in this section.")
    estimated_length: Optional[int] = Field(None, gt=0, description="Estimated word or character length for this section.")


class ContentPlanOutput(BaseModel):
    """
    Structured output generated by the AI Content Planner Agent.
    """
    title: str = Field(..., min_length=1, description="The proposed title of the content.")
    content_goal: str = Field(..., min_length=1, description="The primary objective of the entire piece.")
    hook: str = Field(..., min_length=1, description="An engaging opening or hook to capture attention.")
    sections: List[ContentSection] = Field(
        ...,
        min_length=2,
        max_length=20,
        description="The structural sections of the content."
    )
    key_message: str = Field(..., min_length=1, description="The core takeaway message.")
    call_to_action: Optional[str] = Field(None, description="The intended CTA for the audience, if applicable.")
    content_type: str = Field(..., min_length=1, description="The format of the content (e.g., Thread, Carousel).")
    tone: str = Field(..., min_length=1, description="The overall tone of the piece.")
    platform: str = Field(..., min_length=1, description="The platform this content is intended for.")
    language: str = Field(..., min_length=1, description="The language of the content.")
    constraints: List[str] = Field(default_factory=list, description="List of hard constraints to follow.")
