"""
app/schemas/ai/fact_check.py

Structured output schema for the Fact Checker Agent.
"""
from enum import Enum
from typing import List
from pydantic import BaseModel, Field


class IssueStatus(str, Enum):
    VERIFIED = "VERIFIED"
    UNSUPPORTED = "UNSUPPORTED"
    CONTRADICTED = "CONTRADICTED"
    UNCERTAIN = "UNCERTAIN"


class OverallStatus(str, Enum):
    PASSED = "PASSED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    FAILED = "FAILED"


class FactCheckIssue(BaseModel):
    """
    A specific factual issue identified by the AI.
    """
    claim: str = Field(..., min_length=1, description="The specific claim that was checked.")
    status: IssueStatus = Field(..., description="The status of the claim against the provided evidence.")
    explanation: str = Field(..., min_length=1, description="An explanation of the finding.")
    evidence: str = Field(..., min_length=1, description="The evidence supporting the status (do not fabricate).")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in this specific finding.")


class FactCheckOutput(BaseModel):
    """
    Structured output generated by the AI Fact Checker Agent.
    """
    overall_status: OverallStatus = Field(..., description="The overall status of the content.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Overall confidence in the fact check.")
    issues: List[FactCheckIssue] = Field(default_factory=list, max_length=20, description="List of identified issues.")
    verified_claims: List[str] = Field(default_factory=list, max_length=20, description="List of claims that were verified.")
    unsupported_claims: List[str] = Field(default_factory=list, max_length=20, description="List of claims that lacked support.")
    recommendations: List[str] = Field(default_factory=list, max_length=10, description="Recommendations for fixing the content.")
