"""
app/schemas/ai/generated_content.py

Structured output schema for the Content Generator Agent.
"""
from typing import List, Optional
from pydantic import BaseModel, Field


class GeneratedContentOutput(BaseModel):
    """
    Structured output generated by the AI Content Generator Agent.
    """
    title: Optional[str] = Field(None, description="The title of the content, if applicable for the platform.")
    content: str = Field(..., min_length=1, description="The main body of the generated content.")
    content_type: str = Field(..., min_length=1, description="The type of content (e.g., Post, Thread, Article).")
    platform: str = Field(..., min_length=1, description="The intended platform for this content.")
    language: str = Field(..., min_length=1, description="The language of the content.")
    hashtags: List[str] = Field(default_factory=list, description="A unique list of hashtags.")
    call_to_action: Optional[str] = Field(None, description="The call to action included in the content.")
    character_count: int = Field(..., ge=0, description="The character count of the content.")
    word_count: int = Field(..., ge=0, description="The word count of the content.")
