"""
app/schemas/ai/hashtag.py

Structured output schema for the Hashtag Agent.
"""
from typing import List
from pydantic import BaseModel, Field


class HashtagItem(BaseModel):
    """
    A generated hashtag with metadata.
    """
    hashtag: str = Field(..., description="The hashtag string itself.")
    relevance_score: float = Field(..., description="Score indicating relevance to the content.")
    category: str = Field(..., description="Category of the hashtag (e.g., broad, niche).")


class HashtagOutput(BaseModel):
    """
    Structured output generated by the AI Hashtag Agent.
    """
    hashtags: List[HashtagItem] = Field(default_factory=list, description="All generated hashtags with metadata.")
    primary_hashtags: List[str] = Field(default_factory=list, description="Top-priority hashtags to include.")
    niche_hashtags: List[str] = Field(default_factory=list, description="Highly specific or niche hashtags.")
    recommendations: List[str] = Field(default_factory=list, description="Usage recommendations.")
