"""
app/schemas/ai/image_prompt.py

Structured output schema for the Image Prompt Agent.
"""
from typing import Optional
from pydantic import BaseModel, Field


class ImagePromptOutput(BaseModel):
    """
    Structured output generated by the AI Image Prompt Agent.
    """
    prompt: str = Field(..., description="The main visual prompt for image generation.")
    negative_prompt: Optional[str] = Field(None, description="Elements to explicitly exclude from the image.")
    visual_style: str = Field(..., description="The overarching visual style (e.g., photorealistic, illustration).")
    composition: str = Field(..., description="Description of the scene composition and layout.")
    aspect_ratio: str = Field(..., pattern=r'^\d+:\d+$', description="The required aspect ratio (e.g., '16:9', '1:1').")
    lighting: str = Field(..., description="Description of lighting conditions.")
    color_palette: str = Field(..., description="The color palette or dominant colors.")
    subject: str = Field(..., description="The main subject of the image.")
    platform: str = Field(..., description="The platform this image is intended for.")
    accessibility_description: str = Field(..., description="Alt text or accessibility description for the image.")
