"""
app/schemas/ai/seo.py

Structured output schema for the SEO Agent.
"""
from typing import List
from pydantic import BaseModel, Field


class SEOOutput(BaseModel):
    """
    Structured output generated by the AI SEO Agent.
    """
    optimized_content: str = Field(..., description="The final SEO-optimized content.")
    seo_score: float = Field(..., description="The SEO score of the content (0.0 to 1.0).")
    primary_keywords: List[str] = Field(..., description="The primary keywords targeted in the content.")
    secondary_keywords: List[str] = Field(default_factory=list, description="Secondary or long-tail keywords.")
    recommendations: List[str] = Field(default_factory=list, description="SEO recommendations.")
    changes: List[str] = Field(default_factory=list, description="List of changes made for optimization.")
