"""
app/schemas/ai/strategy.py

Structured output schema for the Strategy Agent.
"""
from typing import List

from pydantic import BaseModel, Field


class StrategyOutput(BaseModel):
    """
    Structured output generated by the AI Strategy Agent.
    """
    content_goal: str = Field(..., description="The primary goal or objective of the content.")
    target_audience: str = Field(..., description="The specific audience this content is intended for.")
    platform_strategy: str = Field(..., description="How to tailor this content specifically for the requested platform.")
    content_type: str = Field(..., description="The recommended format (e.g., Thread, Carousel, Short Video).")
    tone: str = Field(..., description="The emotional tone of the content.")
    language: str = Field(..., description="The language the content should be written in.")
    call_to_action: str = Field(..., description="The primary action the audience should take.")
    constraints: List[str] = Field(default_factory=list, description="List of hard constraints (e.g., max length, forbidden topics).")
