export interface CountryPlatformData {
  country: string;
  flag: string;
  code: string;
  platforms: string[];
}

export const countryPlatforms: CountryPlatformData[] = [
  { country: "Global (Default)", flag: "🌐", code: "un", platforms: ["X / Twitter", "LinkedIn", "Instagram", "Facebook", "TikTok", "YouTube", "Threads", "Bluesky"] },
  { country: "India", flag: "🇮🇳", code: "in", platforms: ["WhatsApp", "YouTube", "Instagram", "Facebook", "Snapchat", "Telegram", "LinkedIn", "X / Twitter", "ShareChat", "Moj", "Josh", "Discord"] },
  { country: "United States", flag: "🇺🇸", code: "us", platforms: ["YouTube", "Facebook", "Instagram", "TikTok", "Snapchat", "Reddit", "X / Twitter", "LinkedIn", "Pinterest", "Discord", "Threads"] },
  { country: "China", flag: "🇨🇳", code: "cn", platforms: ["WeChat", "Douyin", "Xiaohongshu", "Kuaishou", "Weibo", "Bilibili", "QQ", "Zhihu", "Baidu Tieba", "Douban"] },
  { country: "Indonesia", flag: "🇮🇩", code: "id", platforms: ["WhatsApp", "YouTube", "Instagram", "TikTok", "Facebook", "Telegram", "X / Twitter"] },
  { country: "Brazil", flag: "🇧🇷", code: "br", platforms: ["WhatsApp", "Instagram", "YouTube", "Facebook", "TikTok", "Telegram", "X / Twitter", "Kwai"] },
  { country: "Russia", flag: "🇷🇺", code: "ru", platforms: ["VK", "Telegram", "YouTube", "Odnoklassniki", "Rutube", "Dzen", "Pikabu"] },
  { country: "Japan", flag: "🇯🇵", code: "jp", platforms: ["LINE", "YouTube", "X / Twitter", "Instagram", "TikTok", "Facebook", "Threads", "Niconico", "Pixiv"] },
  { country: "Mexico", flag: "🇲🇽", code: "mx", platforms: ["WhatsApp", "Facebook", "YouTube", "Instagram", "TikTok", "Messenger", "X / Twitter"] },
  { country: "Philippines", flag: "🇵🇭", code: "ph", platforms: ["Facebook", "Messenger", "YouTube", "TikTok", "Instagram", "WhatsApp", "X / Twitter"] },
  { country: "Vietnam", flag: "🇻🇳", code: "vn", platforms: ["Facebook", "Zalo", "YouTube", "TikTok", "Instagram", "Messenger"] },
  { country: "Turkey", flag: "🇹🇷", code: "tr", platforms: ["Instagram", "YouTube", "TikTok", "WhatsApp", "Facebook", "X / Twitter", "Telegram"] },
  { country: "Germany", flag: "🇩🇪", code: "de", platforms: ["WhatsApp", "Instagram", "YouTube", "Facebook", "TikTok", "X / Twitter", "LinkedIn", "Reddit"] },
  { country: "United Kingdom", flag: "🇬🇧", code: "gb", platforms: ["YouTube", "Facebook", "Instagram", "TikTok", "WhatsApp", "Snapchat", "X / Twitter", "Reddit", "LinkedIn"] },
  { country: "France", flag: "🇫🇷", code: "fr", platforms: ["YouTube", "Instagram", "Facebook", "WhatsApp", "Snapchat", "TikTok", "X / Twitter", "LinkedIn"] },
  { country: "South Korea", flag: "🇰🇷", code: "kr", platforms: ["KakaoTalk", "YouTube", "Instagram", "Naver", "TikTok", "Facebook", "X / Twitter", "BAND", "SOOP"] },
  { country: "Canada", flag: "🇨🇦", code: "ca", platforms: ["YouTube", "Facebook", "Instagram", "TikTok", "Snapchat", "Reddit", "X / Twitter", "LinkedIn", "Pinterest"] },
  { country: "Australia", flag: "🇦🇺", code: "au", platforms: ["YouTube", "Facebook", "Instagram", "TikTok", "Snapchat", "Reddit", "LinkedIn", "X / Twitter"] },
  { country: "Thailand", flag: "🇹🇭", code: "th", platforms: ["LINE", "Facebook", "YouTube", "TikTok", "Instagram", "X / Twitter"] },
  { country: "Taiwan", flag: "🇹🇼", code: "tw", platforms: ["LINE", "YouTube", "Facebook", "Instagram", "TikTok", "Threads", "Dcard", "X / Twitter"] },
  { country: "Malaysia", flag: "🇲🇾", code: "my", platforms: ["WhatsApp", "Facebook", "Instagram", "YouTube", "TikTok", "Telegram", "X / Twitter"] },
  { country: "Singapore", flag: "🇸🇬", code: "sg", platforms: ["WhatsApp", "YouTube", "Instagram", "Facebook", "TikTok", "Telegram", "LinkedIn", "X / Twitter"] },
  { country: "Saudi Arabia", flag: "🇸🇦", code: "sa", platforms: ["Snapchat", "YouTube", "Instagram", "TikTok", "WhatsApp", "X / Twitter", "Telegram"] },
  { country: "UAE", flag: "🇦🇪", code: "ae", platforms: ["WhatsApp", "Instagram", "YouTube", "TikTok", "Facebook", "Snapchat", "Telegram", "LinkedIn", "X / Twitter"] },
  { country: "South Africa", flag: "🇿🇦", code: "za", platforms: ["WhatsApp", "Facebook", "YouTube", "Instagram", "TikTok", "X / Twitter", "LinkedIn"] },
  { country: "Nigeria", flag: "🇳🇬", code: "ng", platforms: ["WhatsApp", "Facebook", "Instagram", "YouTube", "TikTok", "X / Twitter", "Telegram"] },
  { country: "Egypt", flag: "🇪🇬", code: "eg", platforms: ["Facebook", "WhatsApp", "YouTube", "Instagram", "TikTok", "Messenger", "Telegram"] },
  { country: "Kenya", flag: "🇰🇪", code: "ke", platforms: ["WhatsApp", "Facebook", "YouTube", "TikTok", "Instagram", "X / Twitter"] },
  { country: "Ghana", flag: "🇬🇭", code: "gh", platforms: ["WhatsApp", "Facebook", "YouTube", "Instagram", "TikTok", "X / Twitter"] },
  { country: "Colombia", flag: "🇨🇴", code: "co", platforms: ["WhatsApp", "Facebook", "Instagram", "YouTube", "TikTok", "X / Twitter"] },
  { country: "Argentina", flag: "🇦🇷", code: "ar", platforms: ["WhatsApp", "Instagram", "YouTube", "Facebook", "TikTok", "X / Twitter"] },
  { country: "Chile", flag: "🇨🇱", code: "cl", platforms: ["WhatsApp", "Instagram", "YouTube", "Facebook", "TikTok", "X / Twitter"] },
  { country: "Peru", flag: "🇵🇪", code: "pe", platforms: ["WhatsApp", "Facebook", "YouTube", "Instagram", "TikTok"] },
  { country: "Netherlands", flag: "🇳🇱", code: "nl", platforms: ["WhatsApp", "Instagram", "YouTube", "Facebook", "TikTok", "LinkedIn"] },
  { country: "Spain", flag: "🇪🇸", code: "es", platforms: ["WhatsApp", "Instagram", "YouTube", "Facebook", "TikTok", "X / Twitter"] },
  { country: "Italy", flag: "🇮🇹", code: "it", platforms: ["WhatsApp", "Instagram", "YouTube", "Facebook", "TikTok", "Telegram"] },
  { country: "Poland", flag: "🇵🇱", code: "pl", platforms: ["YouTube", "Facebook", "Instagram", "TikTok", "Messenger", "WhatsApp"] },
  { country: "Sweden", flag: "🇸🇪", code: "se", platforms: ["YouTube", "Instagram", "Facebook", "Snapchat", "TikTok", "LinkedIn"] },
  { country: "Norway", flag: "🇳🇴", code: "no", platforms: ["YouTube", "Snapchat", "Instagram", "Facebook", "TikTok", "LinkedIn"] },
  { country: "Denmark", flag: "🇩🇰", code: "dk", platforms: ["YouTube", "Facebook", "Instagram", "Snapchat", "TikTok"] },
  { country: "Finland", flag: "🇫🇮", code: "fi", platforms: ["YouTube", "Instagram", "Facebook", "Snapchat", "TikTok"] },
  { country: "Israel", flag: "🇮🇱", code: "il", platforms: ["WhatsApp", "YouTube", "Instagram", "Facebook", "TikTok", "Telegram"] },
  { country: "Ireland", flag: "🇮🇪", code: "ie", platforms: ["Instagram", "YouTube", "Facebook", "TikTok", "Snapchat", "WhatsApp"] },
  { country: "New Zealand", flag: "🇳🇿", code: "nz", platforms: ["Facebook", "YouTube", "Instagram", "TikTok", "Snapchat", "Reddit"] },
  { country: "Portugal", flag: "🇵🇹", code: "pt", platforms: ["Facebook", "Instagram", "YouTube", "WhatsApp", "TikTok"] },
  { country: "Greece", flag: "🇬🇷", code: "gr", platforms: ["Facebook", "Instagram", "YouTube", "TikTok", "Messenger"] },
  { country: "Czechia", flag: "🇨🇿", code: "cz", platforms: ["Facebook", "YouTube", "Instagram", "TikTok", "WhatsApp"] },
  { country: "Romania", flag: "🇷🇴", code: "ro", platforms: ["Facebook", "YouTube", "Instagram", "TikTok", "WhatsApp"] },
  { country: "Hungary", flag: "🇭🇺", code: "hu", platforms: ["Facebook", "YouTube", "Instagram", "TikTok", "Messenger"] },
  { country: "Austria", flag: "🇦🇹", code: "at", platforms: ["WhatsApp", "YouTube", "Instagram", "Facebook", "TikTok"] },
  { country: "Switzerland", flag: "🇨🇭", code: "ch", platforms: ["WhatsApp", "Instagram", "YouTube", "Facebook", "LinkedIn", "TikTok"] },
  { country: "Belgium", flag: "🇧🇪", code: "be", platforms: ["Facebook", "Instagram", "YouTube", "WhatsApp", "TikTok"] },
  { country: "Morocco", flag: "🇲🇦", code: "ma", platforms: ["Facebook", "YouTube", "Instagram", "TikTok", "WhatsApp"] },
  { country: "Pakistan", flag: "🇵🇰", code: "pk", platforms: ["WhatsApp", "Facebook", "YouTube", "TikTok", "Instagram", "X / Twitter"] },
  { country: "Bangladesh", flag: "🇧🇩", code: "bd", platforms: ["Facebook", "YouTube", "WhatsApp", "TikTok", "Instagram"] },
  { country: "Sri Lanka", flag: "🇱🇰", code: "lk", platforms: ["Facebook", "YouTube", "WhatsApp", "TikTok", "Instagram"] },
  { country: "Nepal", flag: "🇳🇵", code: "np", platforms: ["Facebook", "YouTube", "TikTok", "Instagram", "WhatsApp"] },
  { country: "Afghanistan", flag: "🇦🇫", code: "af", platforms: ["Facebook", "WhatsApp", "YouTube", "TikTok"] },
  { country: "Cambodia", flag: "🇰🇭", code: "kh", platforms: ["Facebook", "YouTube", "TikTok", "Telegram", "Instagram"] },
  { country: "Myanmar", flag: "🇲🇲", code: "mm", platforms: ["Facebook", "TikTok", "YouTube", "Telegram"] },
  { country: "Laos", flag: "🇱🇦", code: "la", platforms: ["Facebook", "TikTok", "YouTube", "WhatsApp"] },
  { country: "Mongolia", flag: "🇲🇳", code: "mn", platforms: ["Facebook", "YouTube", "Instagram", "TikTok"] },
  { country: "Kazakhstan", flag: "🇰🇿", code: "kz", platforms: ["Instagram", "TikTok", "YouTube", "Telegram", "VK", "WhatsApp"] },
  { country: "Uzbekistan", flag: "🇺🇿", code: "uz", platforms: ["Telegram", "Instagram", "YouTube", "TikTok", "Facebook"] },
  { country: "Ukraine", flag: "🇺🇦", code: "ua", platforms: ["Telegram", "Instagram", "YouTube", "TikTok", "Facebook"] },
  { country: "Georgia", flag: "🇬🇪", code: "ge", platforms: ["Facebook", "Instagram", "YouTube", "TikTok", "Telegram"] },
  { country: "Armenia", flag: "🇦🇲", code: "am", platforms: ["Facebook", "Instagram", "YouTube", "TikTok", "Telegram"] },
  { country: "Azerbaijan", flag: "🇦🇿", code: "az", platforms: ["Instagram", "TikTok", "YouTube", "Facebook", "Telegram"] },
  { country: "Serbia", flag: "🇷🇸", code: "rs", platforms: ["Instagram", "Facebook", "YouTube", "TikTok", "WhatsApp"] },
  { country: "Croatia", flag: "🇭🇷", code: "hr", platforms: ["Facebook", "Instagram", "YouTube", "TikTok", "WhatsApp"] },
  { country: "Slovenia", flag: "🇸🇮", code: "si", platforms: ["Facebook", "Instagram", "YouTube", "TikTok"] },
  { country: "Bulgaria", flag: "🇧🇬", code: "bg", platforms: ["Facebook", "YouTube", "Instagram", "TikTok", "Viber"] },
  { country: "Slovakia", flag: "🇸🇰", code: "sk", platforms: ["Facebook", "Instagram", "YouTube", "TikTok", "WhatsApp"] },
  { country: "Panama", flag: "🇵🇦", code: "pa", platforms: ["WhatsApp", "Instagram", "Facebook", "YouTube", "TikTok"] },
  { country: "Costa Rica", flag: "🇨🇷", code: "cr", platforms: ["WhatsApp", "Facebook", "Instagram", "YouTube", "TikTok"] },
  { country: "Dominican Republic", flag: "🇩🇴", code: "do", platforms: ["WhatsApp", "Instagram", "Facebook", "YouTube", "TikTok"] },
  { country: "Uruguay", flag: "🇺🇾", code: "uy", platforms: ["WhatsApp", "Instagram", "Facebook", "YouTube", "TikTok"] },
  { country: "Ecuador", flag: "🇪🇨", code: "ec", platforms: ["WhatsApp", "Facebook", "Instagram", "YouTube", "TikTok"] }
];
