"""Add post scheduling fields

Revision ID: 0250b6e062bf
Revises: 007
Create Date: 2026-08-14 13:11:58.027600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0250b6e062bf'
down_revision: Union[str, Sequence[str], None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishing_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('platform', postgresql.ENUM('X', 'LINKEDIN', 'INSTAGRAM', 'FACEBOOK', 'THREADS', 'BLUESKY', name='socialplatform', create_type=False), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('external_post_id', sa.String(length=255), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='publishstatus'), nullable=False),
    sa.Column('error_code', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_logs_idempotency_key'), 'publishing_logs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_publishing_logs_social_account_id'), 'publishing_logs', ['social_account_id'], unique=False)
    op.create_index(op.f('ix_publishing_logs_workspace_id'), 'publishing_logs', ['workspace_id'], unique=False)
    op.create_table('approval_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('action', postgresql.ENUM('SUBMIT', 'APPROVE', 'REJECT', name='approvalaction'), nullable=False),
    sa.Column('previous_status', postgresql.ENUM('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'SCHEDULED', 'PUBLISHED', 'FAILED', 'ARCHIVED', name='poststatus', create_type=False), nullable=False),
    sa.Column('new_status', postgresql.ENUM('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'SCHEDULED', 'PUBLISHED', 'FAILED', 'ARCHIVED', name='poststatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_logs_post_id'), 'approval_logs', ['post_id'], unique=False)
    op.create_index(op.f('ix_approval_logs_workspace_id'), 'approval_logs', ['workspace_id'], unique=False)
    op.add_column('posts', sa.Column('timezone', sa.String(length=50), nullable=True))
    
    # Create the schedulingstatus enum explicitly before adding the column
    scheduling_status_enum = postgresql.ENUM('NOT_SCHEDULED', 'SCHEDULED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='schedulingstatus')
    scheduling_status_enum.create(op.get_bind())
    
    op.add_column('posts', sa.Column('scheduling_status', postgresql.ENUM('NOT_SCHEDULED', 'SCHEDULED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='schedulingstatus', create_type=False), nullable=False))
    op.add_column('posts', sa.Column('scheduled_attempts', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('approval_status', sa.String(length=50), nullable=True))
    op.add_column('posts', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('posts', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_posts_scheduled_at'), table_name='posts')
    op.create_foreign_key(None, 'posts', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_index(op.f('ix_posts_scheduled_at'), 'posts', ['scheduled_at'], unique=False)
    op.drop_column('posts', 'rejection_reason')
    op.drop_column('posts', 'approved_at')
    op.drop_column('posts', 'approved_by')
    op.drop_column('posts', 'approval_status')
    op.drop_column('posts', 'failure_reason')
    op.drop_column('posts', 'last_attempt_at')
    op.drop_column('posts', 'scheduled_attempts')
    op.drop_column('posts', 'scheduling_status')
    
    # Drop the enum type created for scheduling status
    postgresql.ENUM(name="schedulingstatus").drop(op.get_bind(), checkfirst=True)
    
    op.drop_column('posts', 'timezone')
    op.drop_index(op.f('ix_approval_logs_workspace_id'), table_name='approval_logs')
    op.drop_index(op.f('ix_approval_logs_post_id'), table_name='approval_logs')
    op.drop_table('approval_logs')
    op.drop_index(op.f('ix_publishing_logs_workspace_id'), table_name='publishing_logs')
    op.drop_index(op.f('ix_publishing_logs_social_account_id'), table_name='publishing_logs')
    op.drop_index(op.f('ix_publishing_logs_idempotency_key'), table_name='publishing_logs')
    op.drop_table('publishing_logs')
    
    # Drop newly created enums (approvalaction and publishstatus)
    postgresql.ENUM(name="approvalaction").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="publishstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
